# Generated by Django 2.1.1 on 2019-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_joke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='is_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='number_of_vote',
            field=models.IntegerField(default=0),
        ),
    ]
