# Generated by Django 2.1.1 on 2019-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_joke', '0002_auto_20190817_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='game_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
