# Generated by Django 2.1.1 on 2019-08-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_joke', '0004_joketext'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='group_chat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joketext',
            name='group_chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
