# Generated by Django 2.2.4 on 2019-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_joke', '0006_auto_20190825_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='current_group_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='group_chat_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
